version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.26.1
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 29
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend